export const API_ENDPOINTS = {
  health: '/health',
  login: '/login',
  changePassword: '/change-password',
  profile: '/profile',
  users: '/users',
  user: (userId: number) => `/users/${userId}`,
  assignUser: '/assign-user',
  projects: '/projects',
  project: (projectId: number) => `/projects/${projectId}`,
  projectData: '/data',
  projectDataById: (dataId: number) => `/data/${dataId}`,
  dashboardData: '/dashboard-data',
  dashboardDataBulk: '/dashboard-data/bulk',
  adminProjects: '/admin/projects',
  adminProjectsStats: '/admin/projects/stats',
  adminProject: (projectId: number) => `/admin/projects/${projectId}`,
  projectReport: (projectId: number) => `/reports/project/${projectId}/summary`,
} as const;
