export const API_ENDPOINTS = {
  health: '/health',
  login: '/login',
  changePassword: '/change-password',
  forgotPassword: '/forgot-password',
  profile: '/profile',
  users: '/users',
  user: (userId: number) => `/users/${userId}`,
  assignUser: '/assign-user',
  projects: '/projects',
  project: (projectId: number) => `/projects/${projectId}`,
  projectData: '/data',
  projectDataById: (dataId: number) => `/data/${dataId}`,
  dashboardData: '/dashboard-data',
  dashboardDataBulk: '/dashboard-data/bulk',
  adminProjects: '/admin/projects',
  adminProjectsStats: '/admin/projects/stats',
  adminProject: (projectId: number) => `/admin/projects/${projectId}`,
  projectReport: (projectId: number) => `/reports/project/${projectId}/summary`,
  payrollModules: '/payroll/modules',
  payrollAttendanceSummary: '/payroll/attendance-summary',
  payrollModuleResolve: '/payroll/modules/resolve',
  payrollLocations: '/payroll/locations',
  payrollCompanies: '/payroll/companies',
  payrollModule: (moduleId: number) => `/payroll/modules/${moduleId}`,
  payrollModuleExport: (moduleId: number) => `/payroll/modules/${moduleId}/export`,
  payrollModuleEmployees: (moduleId: number) => `/payroll/modules/${moduleId}/employees`,
  payrollEmployee: (employeeId: number) => `/payroll/employees/${employeeId}`,
} as const;
